ID: 'AFNOCast-1024-ts-ls_0-fd_12-L1-v1'
Experiment: 'AFNOCast-1024-ts-ls_0-fd_12-L1-v1'

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  prefetch_factor: 16
  train_length: 16000
  val_length: 1600
  field_size: 128
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 16
  seed: 0
  load_full: True

Encoder:
  in_dim: 14
  levels: 3
  extra_resblock_levels: []
  downsampling_mode: "stride"
  norm:
  min_ch: 
  max_ch: 
  channels: [128, 1024]
  kernel_sizes: [[2,1,1], [1,4,4]]
  resample_factors: [[2,1,1], [1,4,4]]
  init: "xavier"

Decoder:
  in_dim: 1024
  out_dim: 11
  levels: 2
  extra_resblock_levels: []
  upsampling_mode: "stride"
  norm:
  min_ch: 128
  max_ch: 1024
  kernel_size: [1,4,4]
  resample_factor: [1,4,4]
  init: "xavier"

Model_Type: "AFNO"

Model:
  in_steps: 2
  embed_dim: 1024
  forecast_depth: 12
  num_blocks: 1
  mlp_ratio: 4
  norm: 
  layer_scale: 0

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/AFNOCast/"
  resume_path: 

Loss:
  Backprop: "L1"
  Monitor: "L1"

Trainer:
  n_steps: 1
  lr: 0.0005
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/AFNOCast/'
  max_epochs: 100
  gradient_clip: .5
  warmup_steps: 5000
  use_cosine: True
  start_cosine_epoch: 15
  T_max: 30
  eta_min: 0.0001
  use_reduce_on_plateau: True
  opt_patience: 3
  dtype: 32