ID: 'AFNONATCast-512-4-parallel'
Experiment: 'AFNONATCast-512-4-parallel'

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  train_length: 128000
  val_length: 12800
  field_size: 256
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 64

Encoder:
  in_dim: 14
  levels: 2
  extra_resblock_levels: [0,1]
  downsampling_mode: "stride"
  norm:
  min_ch: 128
  max_ch: 512
  kernel_sizes: [[2,3,3],[1,3,3]]
  resample_factors: [[2,2,2], [1,2,2]]

Decoder:
  in_dim: 512
  levels: 2
  extra_resblock_levels: [0,1]
  upsampling_mode: "stride"
  norm:
  min_ch: 128
  max_ch: 512
  kernel_size: [1,3,3]
  resample_factor: [1,2,2]

Model_Type: "AFNONAT"

Model:
  in_steps: 2
  embed_dim: 512
  forecast_depth: 4
  afno_num_blocks: 4
  nat_num_blocks: 1
  mlp_ratio: 4
  afno_norm: 
  nat_norm:
  kernel_size: [5, 5, 3, 3]
  layer_scale: "auto"
  mode: "parallel"

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/AFNONATCast/"
  resume_path: 

Loss:
  type: "L1"

Trainer:
  opt_patience: 3
  lr: 0.001
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/AFNONATCast/'
  max_epochs: 100
  n_steps: 1