ID: 'AFNOCast-1024-s2-tss-ls_0-fd_4-L1-v1'
Experiment: 'AFNOCast-1024-s2-tss-ls_0-fd_4-L1-v1'

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  prefetch_factor: 16
  train_length: 32000
  val_length: 3200
  field_size: 256
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 64
  seed: 0
  load_full: True

Encoder:
  in_dim: 14
  levels: 3
  extra_resblock_levels: []
  downsampling_mode: "stride"
  norm:
  min_ch: 
  max_ch: 
  channels: [128, 256, 512]
  kernel_sizes: [[2,1,1], [1,3,3], [1,3,3]]
  resample_factors: [[2,1,1], [1,2,2], [1,2,2]]
  init: "xavier"

Decoder:
  in_dim: 512
  out_dim: 11
  levels: 2
  extra_resblock_levels: []
  upsampling_mode: "stride"
  norm:
  min_ch: 128
  max_ch: 512
  kernel_size: [1,3,3]
  resample_factor: [1,2,2]
  init: "xavier"

Model_Type: "AFNO"

Model:
  in_steps: 2
  embed_dim: 512
  forecast_depth: 1
  num_blocks: 1
  mlp_ratio: 4
  norm: 
  layer_scale: 0

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/AFNOCast/"
  resume_path: "/capstor/scratch/cscs/acarpent/Checkpoints/AFNOCast/AFNOCast-512-s2-tss-ls_0-fd_1-v2/AFNOCast-512-s2-tss-ls_0-fd_1-v2_19.pt"

Loss:
  Backprop: "L1"
  Monitor: "L1"

Trainer:
  opt_patience: 3
  lr: 0.001
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/AFNOCast/'
  max_epochs: 100
  n_steps: 1
  gradient_clip: 1
  warmup_steps: 2000