ID: 'AFNONATCast-1024-s2-tss-ls_0-fd_12-ks_5-seq-L1-v1'
Experiment: 'AFNONATCast-1024-s2-tss-ls_0-fd_12-ks_5-seq-L1-v1'

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  prefetch_factor: 16
  train_length: 16000
  val_length: 1600
  field_size: 256
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 16
  seed: 0
  load_full: True
  dtype: 16

Encoder:
  in_dim: 14
  levels: 3
  extra_resblock_levels: []
  downsampling_mode: "stride"
  norm:
  min_ch: 
  max_ch: 
  channels: [128, 256, 1024]
  kernel_sizes: [[2,1,1],[1,3,3],[1,3,3]]
  resample_factors: [[2,1,1],[1,2,2],[1,2,2]]
  init: "xavier"

Decoder:
  in_dim: 1024
  out_dim: 11
  levels: 2
  extra_resblock_levels: []
  upsampling_mode: "stride"
  norm:
  min_ch: 128
  max_ch: 1024
  kernel_size: [1,3,3]
  resample_factor: [1,2,2]
  init: "xavier"

Model_Type: "AFNONAT"

Model:
  in_steps: 2
  embed_dim: 1024
  forecast_depth: 12
  afno_num_blocks: 1
  nat_num_blocks: 1
  mlp_ratio: 4
  afno_norm: 
  nat_norm:
  kernel_size: 5
  layer_scale: 0.
  mode: "sequential"

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/AFNONATCast/"
  resume_path: #"/capstor/scratch/cscs/acarpent/Checkpoints/AFNONATCast/AFNONATCast-1024-s2-tss-ls_0-fd_8-ks_5-seq-L1-v1/AFNONATCast-1024-s2-tss-ls_0-fd_8-ks_5-seq-L1-v1_26.pt"
  finetune_path: #"/capstor/scratch/cscs/acarpent/Checkpoints/AFNONATCast/AFNONATCast-1024-s2-tss-ls_0-fd_8-ks_5-seq-L1-v1/AFNONATCast-1024-s2-tss-ls_0-fd_8-ks_5-seq-L1-v1_27.pt"

Loss:
  Backprop: "L1"
  Monitor: "L1"

Trainer:
  n_steps: 1
  lr: 0.0005
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/AFNONATCast/'
  max_epochs: 100
  gradient_clip: 1
  warmup_steps: 4000
  use_cosine: True
  start_cosine_epoch: 10
  T_max: 20
  eta_min: 0.00001
  use_reduce_on_plateau: True
  opt_patience: 3
  