ID: 'predrnn-v3'
Experiment: 'predrnn-v3'

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  prefetch_factor: 16
  train_length: 128000
  val_length: 12800
  field_size: 64
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 64
  seed: 0
  load_full: True

Model:
  in_steps: 2
  in_ch: 11 
  out_ch: 11
  num_hidden: [128,128,128]
  tln: False

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/PredRNN/"
  resume_path: 

Loss:
  type: "L1"

Trainer:
  opt_patience: 3
  lr: 0.001
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/PredRNN/'
  max_epochs: 100
  n_steps: 1
  gradient_clip:
  warmup_steps: 