ID: 'predformer-1024-Nds2-h8-hdim128'
Experiment: 'predformer-1024-Nds2-h8-hdim128'

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  prefetch_factor: 16
  train_length: 16000
  val_length: 1600
  field_size: 128
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 16
  seed: 0
  load_full: True

Model_Type: PredFormer

Model:
  patch_size: 8
  pre_seq: 2
  dim: 1024
  in_channels: 14
  out_channels: 11
  heads: 8
  dim_head: 128
  dropout: 0.1
  attn_dropout: 0.1
  drop_path: 0.25
  scale_dim: 2
  Ndepth: 2
  in_steps: 2

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/predformer/"
  resume_path: 
  finetune_path:

Loss:
  Backprop: "L1"
  Monitor: "L1"

Trainer:
  n_steps: 1
  lr: 0.0005
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/predformer/'
  max_epochs: 100
  gradient_clip: .5
  warmup_steps: 10000
  use_cosine: True
  start_cosine_epoch: 10
  T_max: 30
  eta_min: 0.0001
  use_reduce_on_plateau: True
  opt_patience: 3
  dtype: 32
