ID: 'benchmark'
seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 1 
  num_workers: 32
  train_length: 160000
  val_length: 16000
  field_size: 256
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 64
  
Encoder:
  in_dim: 11
  levels: 2
  min_ch: 128
  max_ch: 128
  downsampling_mode: 'stride'
  extra_resblock_levels: [0, 1]
  norm:

Decoder: 
  levels: 2
  min_ch: 128
  max_ch: 128
  upsampling_mode: 'stride'
  extra_resblock_levels: [0, 1]
  norm:

VAE:
  lr: 0.0001
  kl_weight: 0.01
  hidden_width: 128
  opt_patience: 3

EarlyStopping:
  patience: 6

Checkpoint:
  dirpath: '/capstor/scratch/cscs/acarpent/Logs/'
  filename: '{epoch}-{val_rec_loss:.5f}-{val_kl_loss:.5f}'
  monitor: 'val_rec_loss'
  every_n_epochs: 1
  save_top_k: 3

Trainer:
  accelerator: 'gpu'
  devices: 4
  max_epochs: 50
  strategy: 'ddp'
  precision: '16-mixed'
  gradient_clip_val: 1
  resume_training: 