ID: "UNATCast-large-ks9_11-nb8-dd0_0_8-ud2_2-spherical_rope-192_384_960gated-L1"  
Experiment: "UNATCast-large-ks9_11-nb8-dd0_0_8-ud2_2-spherical_rope-192_384_960gated-L1"  

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 3
  num_workers: 16
  prefetch_factor: 16
  train_length: 16000
  val_length: 1600
  field_size: 128
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 16
  seed: 0
  load_full: True
  dtype: 16
  add_latlon: True

Model_Type: "UNAT"

Model:
  in_steps: 2
  in_channels: 14
  out_channels: 11
  down_channels: [192, 576, 960]
  down_mlp_ratio: [4, 4, 2]
  down_gated: [False, False, True]
  down_strides: [[2,1,1], [1,2,2], [1,2,2]]
  down_block_depths: [0, 0, 8]
  down_kernel_sizes: [[0,0], [0,0], [9,9]]
  up_channels: [576, 192]
  up_gated: [False, False]
  up_mlp_ratio: [4, 4]
  up_strides: [[1,2,2],[1,2,2]]
  up_block_depths: [2,2]
  up_kernel_sizes: [[11,11], [11,11]]
  skip_type: "layer_scale"
  skip_down_levels: [0,1]
  skip_up_levels: [0,1]
  num_blocks: 8
  layer_scale: "normal"
  final_conv: True
  resolution: [1, 1]
  emb_method: "spherical_rope"
  downsample_type: ["conv", "avgpool", "avgpool"]   
  upsample_type: "interp"  
  interp_mode: "nearest"

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/UNATCast-large/"
  resume_path:
  finetune_path: 

Loss:
  Backprop: "L1"
  Monitor: "L1"

Trainer:
  n_steps: 1
  lr: 0.0005
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/UNATCast-large/'
  max_epochs: 100
  gradient_clip: .5
  warmup_steps: 5000
  use_cosine: True
  start_cosine_epoch: 10
  T_max: 30
  eta_min: 0.0001
  use_reduce_on_plateau: True
  opt_patience: 3
  dtype: 32
  