ID: "UNATCast-large-ks13-nb1-dd4_4_4-ud4_4-spherical_rope-192_768_768-L1-finetuned"  
Experiment: "UNATCast-large-ks13-nb1-dd4_4_4-ud4_4-spherical_rope-192_768_768-L1-finetuned" 

seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 8
  num_workers: 16
  prefetch_factor: 16
  train_length: 16000
  val_length: 1600
  field_size: 256
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 16
  seed: 0
  load_full: True
  dtype: 16
  add_latlon: True

Model_Type: "UNAT"

Model:
  in_steps: 2
  in_channels: 14
  out_channels: 11
  down_channels: [192, 768, 768]
  down_strides: [[2,1,1], [1,2,2], [1,2,2]]
  down_block_depths: [4,4,4]
  down_kernel_sizes: [[13,13], [13,13], [13,13]]
  up_channels: [768, 192]
  up_strides: [[1,2,2], [1,2,2]]
  up_block_depths: [4,4]
  up_kernel_sizes: [[13,13], [13,13]]
  skip_type: "layer_scale"
  skip_down_levels: [1]
  skip_up_levels: [0]
  mlp_ratio: 4
  num_blocks: 1
  layer_scale: 0
  final_conv: True
  resolution: [1, 1]
  emb_method: "spherical_rope"
  downsample_type: ["conv", "avgpool", "avgpool"]   
  upsample_type: "interp"  
  interp_mode: "nearest"

Checkpoint:
  dirpath: "/capstor/scratch/cscs/acarpent/Checkpoints/UNATCast-large/"
  resume_path: 
  finetune_path: "/capstor/scratch/cscs/acarpent/Checkpoints/UNATCast-large/UNATCast-large-ks13-nb1-dd4_4_4-ud4_4-spherical_rope-192_768_768-L1/UNATCast-large-ks13-nb1-dd4_4_4-ud4_4-spherical_rope-192_768_768-L1_99.pt"

Loss:
  Backprop: "L1"
  Monitor: "L1"

Trainer:
  n_steps: 1
  lr: 0.0001
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/UNATCast-large/'
  max_epochs: 100
  gradient_clip: .5
  warmup_steps: 5000
  use_cosine: False
  start_cosine_epoch: 16
  T_max: 30
  eta_min: 0.00005
  use_reduce_on_plateau: True
  opt_patience: 3
  dtype: 32
  