ID: 'VAE-1'
Experiment: 'VAE-128-0.01'
seed: 0
Dataset:
  data_path: '/capstor/scratch/cscs/acarpent/SEVIRI'
  invariants_path: '/capstor/scratch/cscs/acarpent/SEVIRI/invariants'
  input_seq_len: 1 
  num_workers: 16
  train_length: 160000
  val_length: 16000
  field_size: 256
  train_years: [2017, 2018, 2019]
  val_years: [2020]
  batch_size: 64
  
Encoder:
  in_dim: 11
  levels: 2
  min_ch: 128
  max_ch: 128
  downsampling_mode: 'stride'
  extra_resblock_levels: [0, 1]
  norm:

Decoder: 
  levels: 2
  min_ch: 128
  max_ch: 128
  upsampling_mode: 'stride'
  extra_resblock_levels: [0, 1]
  norm:

VAE:
  hidden_width: 128

EarlyStopping:
  patience: 6

Checkpoint:
  dirpath: '/capstor/scratch/cscs/acarpent/Logs/VAE/'
  resume_path:

Loss:
  kl_weight: 0.01

Trainer:
  opt_patience: 3
  lr: 0.0001
  log_dir: '/capstor/scratch/cscs/acarpent/Logs/VAE/'
  max_epochs: 100